name: 'Setup Python Environment'
description: 'Checkout, setup Python, and install dependencies'
inputs:
  python-reusable:
    description: 'Python version to use'
    required: true
runs:
  using: 'composite'
  steps:

    - name: Checkout repository code
      uses: actions/checkout@v4
        
    - name: Set up Python ${{ inputs.python-reusable }}
      uses: actions/setup-python@v5
      with:
          python-version: ${{ inputs.python-reusable }}
          cache: 'pip'
           
    - name: Install test
      shell: bash
      run: pip install -r requirements.txt  

   