name: Python Linting Pipeline
on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]
jobs:
  Download_repo_and_run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        
      - name: Run script
        run: echo "Hello World"
  
  Setup_Python_and_run_test:
    needs: Download_repo_and_run_script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install test
        run: pip install pytest  

      - name: Run test
        run: pytest test_*.py  
     