name: Python Linting Pipeline
on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]
jobs:
  Download_repo_and_run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        
      - name: Run script
        run: echo "Hello World"
  
  Setup_Python_and_run_test:
    needs: Download_repo_and_run_script
    strategy:
      matrix:
        python-version: [3.14, 3.13, 3.12]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
           
      - name: Install test
        run: pip install -r requirements.txt  

      - name: Run test
        run: pytest tests/  

  Build_Docker_image:
    needs: Setup_Python_and_run_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: | 
           docker build -t milorad86/myy-app:latest .
        #   docker build -t milorad86/myy-app:latest -t milorad86/myy-app:${{github.sha}} .
           


      - name: Push Docker image
        run: |
           docker push milorad86/myy-app:latest
        #  docker push milorad86/myy-app:${{github.sha}}


  Deploy_to_Staging:
    needs: Build_Docker_image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Deploy to Render
        run: |
          curl -fX POST "${{ secrets.RENDER_STAGING_DEPLOY_HOOK }}"
  
  
  Deploy_to_Production:
    needs: Deploy_to_Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Deploy to Render
        run: |
          curl -fX POST "${{ secrets.RENDER_PROD_DEPLOY_HOOK }}"